declare namespace msgidrummy{

    const PACKAGE_NAME = 'msgid';

    /** RummyMsgID 消息 ID */
    enum RummyMsgID{
        /**  网关认证请求 */
        GateAuthReq = 4097,
        /**  网关认证应答 */
        GateAuthRsp = 4098,
        /**  心跳检测请求 */
        GateHeartBeatReq = 4099,
        /**  心跳检测应答 */
        GateHeartBeatRsp = 4100,
        /**  顶号通知 */
        GateAnotherLoginNtf = 4101,
        /**  转发消息失败通知 */
        GateTransferMsgFailNtf = 4102,
        /**  未登陆通知 */
        GateNoLoginNtf = 4103,
        /**  转发平台 http 请求 */
        GateTransmitHTTPReq = 4113,
        /**  转发平台 http 应答 */
        GateTransmitHTTPRsp = 4114,
        /**  注册请求 */
        GateRegisterReq = 4115,
        /**  注册应答 */
        GateRegisterRsp = 4116,
        /**  发送短信验证码请求 */
        GateSendSmsCodeReq = 4117,
        /**  发送短信验证码应答 */
        GateSendSmsCodeRsp = 4118,
        /**  获取图形验证码请求 */
        GateGetPicCodeReq = 4119,
        /**  获取图形验证码应答 */
        GateGetPicCodeRsp = 4120,
        /**  找回密码请求 */
        GateResetPasswordReq = 4121,
        /**  找回密码请求应答 */
        GateResetPasswordRsp = 4122,
        /**  获取跑马灯请求 */
        MsgSvrGetHorseRaceReq = 16385,
        /**  获取跑马灯应答 */
        MsgSvrGetHorseRaceRsp = 16386,
        /**  跑马灯变化通知 */
        MsgSvrHorseRaceUpdateNtf = 16387,
        /**  获取slot主题列表请求 */
        GetSlotThemeListReq = 16897,
        /**  获取slot主题列表请求应答 */
        GetSlotThemeListRsp = 16898,
        /**  获取slot场次列表请求 */
        GetSlotLevelListReq = 16899,
        /**  获取slot场次列表请求应答 */
        GetSlotLevelListRsp = 16900,
        /**  进入slot指定场次请求 */
        EnterSlotThemeReq = 16901,
        /**  进入slot指定场次请求应答 */
        EnterSlotThemeRsp = 16902,
        /**  离开slot指定场次请求 */
        LeaveSlotThemeReq = 16903,
        /**  离开slot指定场次请求应答 */
        LeaveSlotThemeRsp = 16904,
        /**  spin slot请求 */
        SpinSlotReq = 16905,
        /**  spin slot请求应答 */
        SpinSlotRsp = 16906,
        /**  定时刷新共享jackpot奖池请求 */
        RefreshSlotJackPotReq = 16907,
        /**  定时刷新共享jackpot奖池请求应答 */
        RefreshSlotJackPotRsp = 16908,
        /**  Spin进入控制通知 */
        SlotEnterControlNtf = 16909,
        /** 进入luckyball请求 */
        EnterLuckyBallReq = 16913,
        /** 进入luckyball请求应答 */
        EnterLuckyBallRsp = 16914,
        /** 离开luckyball请求 */
        LeaveLuckyBallReq = 16915,
        /** 离开luckyball请求应答 */
        LeaveLuckyBallRsp = 16916,
        /** 摇球请求 */
        LuckyBallBetReq = 16917,
        /** 摇球请求应答 */
        LuckyBallBetRsp = 16918,
        /**  假百人信息请求 */
        EnterJiabairenReq = 16919,
        /**  假百人信息应答 */
        EnterJiabairenRsp = 16920,
        /**  提醒玩家充值通知 */
        FreeRemindRechargeNtf = 16921,
        /**  super spin请求 */
        SlotSuperSpinReq = 16922,
        /**  super spin请求应答 */
        SlotSuperSpinRsp = 16923,
        /**  进入扫雷请求 */
        EnterMinesReq = 16929,
        /**  进入扫雷请求应答 */
        EnterMinesRsp = 16930,
        /**  下注并开始扫雷请求 */
        StartMinesReq = 16931,
        /**  下注并开始扫雷请求应答 */
        StartMinesRsp = 16932,
        /**  扫雷请求 */
        OpenMinesReq = 16933,
        /**  扫雷请求应答 */
        OpenMinesRsp = 16934,
        /**  扫雷下车请求 */
        CashOutMinesReq = 16935,
        /**  扫雷下车请求应答 */
        CashOutMinesRsp = 16936,
        /**  离开扫雷请求 */
        LeaveMinesReq = 16937,
        /**  离开扫雷请求应答 */
        LeaveMinesRsp = 16938,
        /**  开奖记录 */
        MinesPlayerHistoryReq = 16939,
        /**  开奖记录应答 */
        MinesPlayerHistoryRsp = 16940,
        /**  进入BinGo请求 */
        EnterBingoReq = 16945,
        /**  进入BinGo请求应答 */
        EnterBingoRsp = 16946,
        /**  离开请求 */
        LeaveBingoReq = 16947,
        /**  离开请求应答 */
        LeaveBingoRsp = 16948,
        /**  刷新卡请求 */
        BingoNewCardReq = 16949,
        /**  刷新卡请求应答 */
        BingoNewCardRsp = 16950,
        /**  Bingo spin请求 */
        BingoSpinReq = 16951,
        /**  Bingo spin请求应答 */
        BingoSpinRsp = 16952,
        /**  Bingo增购请求 */
        BingoAddReq = 16953,
        /**  Bingo增购请求应答 */
        BingoAddRsp = 16954,
        /**  Bingo结算请求 */
        BingoCashOutReq = 16955,
        /**  Bingo结算请求应答 */
        BingoCashOutRsp = 16956,
        /**  Bingo开关卡片请求 */
        BingoOpenCardReq = 16957,
        /**  Bingo开关卡片请求应答 */
        BingoOpenCardRsp = 16958,
        /**  消除slot请求 */
        SpinCancleSlotReq = 16961,
        /**  消除slot返回 */
        SpinCancleSlotRsp = 16962,
        /**  购买freegame请求 */
        CancleSlotBuyFreeReq = 16963,
        /**  购买freegame返回 */
        CancleSlotBuyFreeRsp = 16964,
        /**  GM命令请求 */
        SlotGMCmdReq = 16965,
        /**  GM命令请求响应 */
        SlotGMCmdRsp = 16966,
        /**  海盗请求 */
        SpinPirateReq = 16967,
        /**  海盗返回 */
        SpinPirateRsp = 16968,
        /**  进入转盘请求 */
        EnterWheelReq = 16969,
        /**  进入转盘响应 */
        EnterWheelRsp = 16970,
        /**  离开转盘请求 */
        LeaveWheelReq = 16971,
        /**  离开转盘响应 */
        LeaveWheelRsp = 16972,
        /**  spin转盘请求 */
        SpinWheelReq = 16973,
        /**  spin转盘返回 */
        SpinWheelRsp = 16974,
        /**  查看转盘spin历史记录请求 */
        ViewWheelPlayerHistoryReq = 16975,
        /**  查看转盘spin历史记录返回 */
        ViewWheelPlayerHistoryRsp = 16976,
        /**  进入请求 */
        EnterPlinkoReq = 16977,
        /**  进入请求应答 */
        EnterPlinkoRsp = 16978,
        /**  离开请求 */
        LeavePlinkoReq = 16979,
        /**  离开请求应答 */
        LeavePlinkoRsp = 16980,
        /**  离开请求 */
        StartPlinkoReq = 16981,
        /**  离开请求应答 */
        StartPlinkoRsp = 16982,
        /**  历史记录请求 */
        PlinkoHistoryReq = 16983,
        /**  历史记录应答 */
        PlinkoHistoryRsp = 16984,
        /**  更新转盘设置请求 */
        UpdateWheelSettingReq = 16987,
        /**  更新转盘设置返回 */
        UpdateWheelSettingRsp = 16988,
        /**  进入原版扫雷请求 */
        EnterMinesOriginReq = 16992,
        /**  进入原版扫雷应答 */
        EnterMinesOriginRsp = 16993,
        /**  下注并开始原版扫雷请求 */
        StartMinesOriginReq = 16994,
        /**  下注并开始原版扫雷应答 */
        StartMinesOriginRsp = 16995,
        /**  原版扫雷开盒请求 */
        OpenMinesOriginReq = 16996,
        /**  原版扫雷开盒应答 */
        OpenMinesOriginRsp = 16997,
        /**  原版扫雷下车请求 */
        CashOutMinesOriginReq = 16998,
        /**  原版扫雷下车应答 */
        CashOutMinesOriginRsp = 16999,
        /**  离开原版扫雷请求 */
        LeaveMinesOriginReq = 17000,
        /**  离开原版扫雷应答 */
        LeaveMinesOriginRsp = 17001,
        /**  原版扫雷修改底注或雷数请求 */
        EditMinesOriginBlindReq = 17002,
        /**  原版扫雷修改底注或雷数应答 */
        EditMinesOriginBlindRsp = 17003,
        /**  原版扫雷开奖记录 */
        MinesOriginPlayerHistoryReq = 17004,
        /**  原版扫雷开奖记录应答 */
        MinesOriginPlayerHistoryRsp = 17005,
        /**  原版扫雷自动开盒请求 */
        AutoOpenMinesOriginReq = 17006,
        /**  原版扫雷自动开盒应答 */
        AutoOpenMinesOriginRsp = 17007,
        /**  进入百人场请求 */
        EnterBaccaratReq = 17153,
        /**  进入百人场请求应答 */
        EnterBaccaratRsp = 17154,
        /**  离开百人场请求 */
        LeaveBaccaratReq = 17155,
        /**  离开百人场请求应答 */
        LeaveBaccaratRsp = 17156,
        /**  百人场下注请求 */
        BetBaccaratReq = 17157,
        /**  百人场下注请求应答 */
        BetBaccaratRsp = 17158,
        /**  最新玩家下注通知消息 */
        BetBaccaratNtf = 17159,
        /**  阶段变化通知消息 */
        BaccaratNextStageNtf = 17160,
        /**  结算通知消息 */
        BaccaratSettleNtf = 17161,
        /**  在线人数变化通知消息 */
        BaccaratOnlineNtf = 17162,
        /**  获取百人场玩家请求 */
        GetBaccaratPlayerListReq = 17163,
        /**  获取百人场玩家请求响应 */
        GetBaccaratPlayerListRsp = 17164,
        /**  暂停百人场请求 */
        PauseBaccaratReq = 17165,
        /**  暂停百人场请求响应 */
        PauseBaccaratRsp = 17166,
        /**  每个区域用户下注累计值 */
        BaccaratAreaUserBetsNtf = 17167,
        /**  LH结算通知消息 */
        BaccaratLongHuSettleNtf = 17168,
        /**  RB结算通知消息 */
        BaccaratRedBlackSettleNtf = 17169,
        /** 开奖结果通知 */
        LotterySettleNtf = 17185,
        /** 玩家历史下注 */
        LotteryPlayerHistoryReq = 17186,
        /** 玩家历史下注 */
        LotteryPlayerHistoryRsp = 17187,
        /** 开奖明文密文 */
        LotteryEncryptedDataReq = 17190,
        /** 开奖明文密文 */
        LotteryEncryptedDataRsp = 17191,
        /** 通用 开奖历史 */
        LotteryHistoryReq = 17192,
        /** 彩票类请求 */
        LotteryHistoryRsp = 17193,
        /** 通用 开奖明密文 */
        EncryptedDataReq = 17194,
        /** 彩票类请求 */
        EncryptedDataRsp = 17195,
        /** 通用 玩家下注历史 */
        PlayerHistoryReq = 17196,
        /** 彩票类请求 */
        PlayerHistoryRsp = 17197,
        /**  小火箭下车请求 */
        RocketCashOutReq = 17198,
        /**  小火箭下车请求响应 */
        RocketCashOutRsp = 17199,
        /**  小火箭爆炸结算通知消息 */
        RocketSettleNtf = 17201,
        /**  小火箭下车通知消息 */
        RocketCashOutNtf = 17202,
        /** 小火箭进度通知 */
        RocketRateNtf = 17203,
        /** 百人场下注取消请求 */
        BetBaccaratCancelReq = 17204,
        /** 百人场下注取消请求响应 */
        BetBaccaratCancelRsp = 17205,
        /**  小火箭 起飞通知消息 */
        RocketFlyNtf = 17206,
        /**  长时间未下注踢出通知消息 */
        BaccaratKickOutNtf = 17207,
        /** 玩家取消自动下车请求 */
        RocketAutoCashOutReq = 17208,
        /** 玩家取消自动下车请求返回 */
        RocketAutoCashOutRsp = 17209,
        /** 小火箭下注记录列表请求 */
        RocketPlayerHistoryReq = 17210,
        /** 小火箭下注记录列表返回 */
        RocketPlayerHistoryRsp = 17211,
        /** 小火箭验证消息请求 */
        RocketEncryptedDataReq = 17212,
        /** 小火箭验证消息返回 */
        RocketEncryptedDataRsp = 17213,
        /** 小火箭对局历史列表请求 */
        RocketDeskHistoryReq = 17214,
        /** 小火箭对局历史列表返回 */
        RocketDeskHistoryRsp = 17216,
        /**  小火箭下车请求 */
        Rocket3DCashOutReq = 17217,
        /**  小火箭下车请求响应 */
        Rocket3DCashOutRsp = 17218,
        /**  小火箭爆炸结算通知消息 */
        Rocket3DSettleNtf = 17219,
        /**  小火箭起飞通知消息 */
        Rocket3DFlyNtf = 17220,
        /**  小火箭下车通知消息 */
        Rocket3DCashOutNtf = 17221,
        /**  小火箭进度通知 */
        Rocket3DRateNtf = 17222,
        /** 玩家取消自动下车请求 */
        Rocket3DAutoCashOutReq = 17223,
        /** 玩家取消自动下车请求返回 */
        Rocket3DAutoCashOutRsp = 17224,
        /** 小火箭下注记录列表请求 */
        Rocket3DPlayerHistoryReq = 17225,
        /** 小火箭下注记录列表返回 */
        Rocket3DPlayerHistoryRsp = 17226,
        /** 小火箭验证消息请求 */
        Rocket3DEncryptedDataReq = 17227,
        /** 小火箭验证消息返回 */
        Rocket3DEncryptedDataRsp = 17228,
        /** 小火箭对局历史列表请求 */
        Rocket3DDeskHistoryReq = 17229,
        /** 小火箭对局历史列表返回 */
        Rocket3DDeskHistoryRsp = 17230,
        /** 龙虎开奖结果通知 */
        LongHuSettleNtf = 17232,
        /** 龙虎玩家历史下注 */
        LongHuPlayerHistoryReq = 17233,
        /** 龙虎玩家历史下注 */
        LongHuPlayerHistoryRsp = 17234,
        /** 洗牌消息 */
        LongHuShuffleCardsNtf = 17241,
        /** 小火箭本局下注玩家列表查看请求 */
        Rocket3DDeskBetsHistoryReq = 17239,
        /** 小火箭本局下注玩家列表查看返回 */
        Rocket3DDeskBetsHistoryRsp = 17240,
        /** 股票玩家历史下注请求 */
        StockPlayerHistoryReq = 17248,
        /** 股票玩家历史下注返回 */
        StockPlayerHistoryRsp = 17249,
        /** 股票验证消息请求 */
        StockEncryptedDataReq = 17250,
        /** 股票验证消息返回 */
        StockEncryptedDataRsp = 17251,
        /** 股票结算通知消息 */
        StockSettleNtf = 17252,
        /** 股票桌子历史信息请求 */
        StockDeskHistoryReq = 17253,
        /** 股票桌子历史信息返回 */
        StockDeskHistoryRsp = 17254,
        /**  获取设备页请求 */
        BatterySvrGetDeviceListReq = 37889,
        /**  获取设备页请求应答 */
        BatterySvrGetDeviceListRsp = 37890,
        /**  投资购买设备请求 */
        BatterySvrBuyReq = 37891,
        /**  投资购买设备请求应答 */
        BatterySvrBuyRsp = 37892,
        /**  获取我的设备页请求 */
        BatterySvrGetMyDeviceReq = 37893,
        /**  获取我的设备页请求应答 */
        BatterySvrGetMyDeviceRsp = 37894,
        /**  赎回设备请求 */
        BatterySvrReturnReq = 37895,
        /**  赎回设备应答 */
        BatterySvrReturnRsp = 37896,
        /**  获取设备记录页请求 */
        BatterySvrGetMyRecordReq = 37897,
        /**  获取设备记录页应答 */
        BatterySvrGetMyRecordRsp = 37898,
        /**  获取会员列表页请求 */
        BatterySvrGetClubLevelReq = 37899,
        /**  获取会员列表页应答 */
        BatterySvrGetClubLevelRsp = 37900,
        /**  获取会员介绍页请求 */
        BatterySvrGetClubInfoPageReq = 37901,
        /**  获取会员介绍页应答 */
        BatterySvrGetClubInfoPageRsp = 37902,
        /**  获取金币流水日志页请求 */
        BatterySvrGetCashRecordReq = 37904,
        /**  获取金币流水日志页请求应答 */
        BatterySvrGetCashRecordRsp = 37905,
        /**  获取首页信息请求 */
        BtcSvrGetHomeInfoReq = 37633,
        /**  获取首页信息请求应答 */
        BtcSvrGetHomeInfoRsp = 37634,
        /**  获取资产实时价格请求 */
        BtcSvrGetAssetPriceReq = 37635,
        /**  获取资产实时价格请求应答 */
        BtcSvrGetAssetPriceRsp = 37636,
        /**  获取下注的订单请求 */
        BtcSvrGetAssetOrderReq = 37637,
        /**  获取下注的订单请求应答 */
        BtcSvrGetAssetOrderRsp = 37638,
        /**  下注请求 */
        BtcSvrBuyReq = 37639,
        /**  下注请求应答 */
        BtcSvrBuyRsp = 37640,
        /**  获取订单记录请求 */
        BtcSvrGetOrderRecordReq = 37641,
        /**  获取订单记录请求应答 */
        BtcSvrGetOrderRecordRsp = 37642,
        /**  获取玩家信息请求 */
        BtcSvrGetPlayerInfoReq = 37643,
        /**  获取玩家信息应答 */
        BtcSvrGetPlayerInfoRsp = 37644,
        /**  获取玩家金币流水请求 */
        BtcSvrGetGoldStatementsReq = 37645,
        /**  获取玩家金币流水应答 */
        BtcSvrGetGoldStatementsRsp = 37646,
        /** 获取玩家充值记录请求 */
        BtcSvrGetRechargeRecordReq = 37648,
        /** 获取玩家充值记录应答 */
        BtcSvrGetRechargeRecordRsp = 37649,
        /** 获取玩家提现记录请求 */
        BtcSvrGetWithdrawRecordReq = 37650,
        /** 获取玩家充值记录应答 */
        BtcSvrGetWithdrawRecordRsp = 37651,
        /** 获取贡献有礼配置请求 */
        BtcSvrGetContributionGiftConfigReq = 37652,
        /** 获取贡献有礼配置应答 */
        BtcSvrGetContributionGiftConfigRsp = 37653,
        /**  金币变化通知消息 */
        BtcSvrMoneyChangeNtf = 37664,
        /** 订单开奖通知 */
        BtcSvrOrderOpenNtf = 37665,
        /**  获取我的团队信息请求 */
        PartnerSvrGetMyTeamReq = 37377,
        /**  获取我的团队信息应答 */
        PartnerSvrGetMyTeamRsp = 37378,
        /**  获取团队报表信息请求 */
        PartnerSvrGetTeamFormsReq = 37379,
        /**  获取团队报表信息应答 */
        PartnerSvrGetTeamFormsRsp = 37380,
        /**  获取日结报表请求 */
        PartnerSvrGetTeamDiaryReq = 37381,
        /**  获取日结报表应答 */
        PartnerSvrGetTeamDiaryRsp = 37382,
        /**  获取代理页请求 */
        PartnerSvrGetAgentPageReq = 37383,
        /**  获取代理页应答 */
        PartnerSvrGetAgentPageRsp = 37384,
        /**  获取团队报表请求 */
        PartnerSvrGetDualityFormsReq = 37385,
        /**  获取团队报表应答 */
        PartnerSvrGetDualityFormsRsp = 37386,
        /**  获取团队成员请求 */
        PartnerSvrGetDualityTeamReq = 37387,
        /**  获取团队成员应答 */
        PartnerSvrGetDualityTeamRsp = 37388,
        /**  获取每日返利请求 */
        PartnerSvrGetDiaryBonusReq = 37389,
        /**  获取每日返利应答 */
        PartnerSvrGetDiaryBonusRsp = 37390,
        /**  获取代理页请求 */
        PartnerSvrGetBatteryAgentPageReq = 37393,
        /**  获取代理页应答 */
        PartnerSvrGetBatteryAgentPageRsp = 37394,
        /**  获取代理收益页请求 */
        PartnerSvrGetMyIncomeReq = 37395,
        /**  获取代理收益页应答 */
        PartnerSvrGetMyIncomeRsp = 37396,
        /**  获取下级好友页请求 */
        PartnerSvrGetReferralsReq = 37397,
        /**  获取下级好友页应答 */
        PartnerSvrGetReferralsRsp = 37398,
        /**  获取团队详情请求 */
        PartnerSvrGetTeamDetailReq = 37399,
        /**  获取团队详情请求应答 */
        PartnerSvrGetTeamDetailRsp = 37400,
        /**  获取大厅的任务列表请求 */
        NetMoneyGetHallTasksReq = 36865,
        /**  获取大厅的任务列表请求应答 */
        NetMoneyGetHallTasksRsp = 36866,
        /**  获取用户领取的任务列表请求 */
        NetMoneyGetUserTasksReq = 36867,
        /**  获取用户领取的任务列表请求应答 */
        NetMoneyGetUserTasksRsp = 36868,
        /**  获取用户发布的任务列表请求 */
        NetMoneyGetPublishTasksReq = 36869,
        /**  获取用户发布的任务列表请求应答 */
        NetMoneyGetPublishTasksRsp = 36870,
        /**  获取玩家发布任务的执行情况请求 */
        NetMoneyGetPublishTaskExecReq = 36871,
        /**  获取玩家发布任务的执行情况请求应答 */
        NetMoneyGetPublishTaskExecRsp = 36872,
        /**  玩家发布任务请求 */
        NetMoneyPublishTaskReq = 36873,
        /**  玩家发布任务请求应答 */
        NetMoneyPublishTaskRsp = 36874,
        /**  玩家领取任务请求 */
        NetMoneyRecvTaskReq = 36875,
        /**  玩家领取任务请求应答 */
        NetMoneyRecvTaskRsp = 36876,
        /**  发布者审核任务请求 */
        NetMoneyAuditTaskReq = 36877,
        /**  发布者审核任务请求应答 */
        NetMoneyAuditTaskRsp = 36878,
        /**  提交任务截图请求 */
        NetMoneySubmitTaskReq = 36880,
        /**  提交任务截图请求应答 */
        NetMoneySubmitTaskRsp = 36881,
        /**  获取玩家资料请求 */
        NetMoneyGetUserInfoReq = 36882,
        /**  获取玩家资料请求应答 */
        NetMoneyGetUserInfoRsp = 36883,
        /**  设置玩家资料请求 */
        NetMoneySetUserInfoReq = 36884,
        /**  设置玩家资料请求应答 */
        NetMoneySetUserInfoRsp = 36885,
        /**  设置资金密码请求 */
        NetMoneySetMoneyPassReq = 36886,
        /**  设置资金密码请求应答 */
        NetMoneySetMoneyPassRsp = 36887,
        /**  获取首页信息请求 */
        NetMoneyGetHomeInfoReq = 36888,
        /**  获取首页信息请求应答 */
        NetMoneyGetHomeInfoRsp = 36889,
        /**  获取用户VIP配置请求 */
        NetMoneyGetUserVipConfigReq = 36896,
        /**  获取用户VIP配置应答 */
        NetMoneyGetUserVipConfigRsp = 36897,
        /**  获取交易流水请求 */
        NetMoneyGetTransactionReq = 36898,
        /**  获取交易流水请求应答 */
        NetMoneyGetTransactionRsp = 36899,
        /**  获取充值记录请求 */
        NetMoneyGetRechargeRecordReq = 36900,
        /**  获取充值记录应答 */
        NetMoneyGetRechargeRecordRsp = 36901,
        /**  获取提现记录请求 */
        NetMoneyGetWithdrawRecordReq = 36902,
        /**  获取提现记录应答 */
        NetMoneyGetWithdrawRecordRsp = 36903,
        /**  发送用户购买VIP请求 */
        NetMoneyBuyVipReq = 36904,
        /**  发送用户购买VIP应答 */
        NetMoneyBuyVipRsp = 36905,
        /**  获取用户排行版请求 */
        NetMoneyGetRankingBoardReq = 36912,
        /**  获取用户排行版应答 */
        NetMoneyGetRankingBoardRsp = 36913,
        /**  获取新vip用户请求 */
        NetMoneyGetNewVipReq = 36914,
        /**  获取新vip用户应答 */
        NetMoneyGetNewVipRsp = 36915,
        /** 获取用户提现信息请求 */
        NetMoneyGetUserWithdrawInfoReq = 36916,
        /** 获取用户提现信息应答 */
        NetMoneyGetUserWithdrawInfoRsp = 36917,
        /**  获取房间列表请求 */
        RBServerGetRoomListReq = 24577,
        /**  获取房间列表应答 */
        RBServerGetRoomListRsp = 24578,
        /**  获取房间当前游戏开奖信息请求 */
        RBServerGetRoomInfoReq = 24579,
        /**  获取房间当前游戏开奖信息应答 */
        RBServerGetRoomInfoRsp = 24580,
        /**  发送用户下注请求 */
        RBServerCreateOrderReq = 24581,
        /**  发送用户下注应答 */
        RBServerCreateOrderRsp = 24582,
        /**  获取用户待开奖订单请求 */
        RBServerGetOrderReq = 24583,
        /**  获取用户待开奖订单应答 */
        RBServerGetOrderRsp = 24584,
        /**  获取用户历史订单请求 */
        RBServerGetOrderHistoryReq = 24585,
        /**  获取用户历史订单应答 */
        RBServerGetOrderHistoryRsp = 24592,
        /**  获取用户历史统计请求 */
        RBServerGetHistoryInfoReq = 24593,
        /**  获取用户历史统计应答 */
        RBServerGetHistoryInfoRsp = 24594,
        /**  获取房间历史开奖请求 */
        RBServerGetRoomHistoryReq = 24595,
        /**  获取房间历史开奖应答 */
        RBServerGetRoomHistoryRsp = 24596,
        /**  请求认证 */
        LoginAuthReq = 1,
        /**  响应认证 */
        LoginAuthRsp = 2,
        /**  修改登录密码请求 */
        LoginModPassReq = 3,
        /**  修改登录密码请求应答 */
        LoginModPassRsp = 4,
        /**  1.rummy进入大厅请求 */
        RummyEnterHallReq = 13312,
        /**  rummy进入大厅回复 */
        RummyEnterHallRsp = 13313,
        /**  2.rummy获取游戏场次列表请求 */
        RummyGetLevelListReq = 13314,
        /**  rummy获取游戏场次列表回复 */
        RummyGetLevelListRsp = 13315,
        /**  3.rummy点击玩家头像，获取玩家信息请求 */
        RummyGetPlayerInfoReq = 13316,
        /**  rummy点击玩家头像，获取玩家信息回复 */
        RummyGetPlayerInfoRsp = 13317,
        /**  金币变化通知消息 */
        RummyMoneyChangeNtf = 13318,
        /**  更新玩家头像昵称请求 */
        RummyUpdatePlayerInfoReq = 13319,
        /**  更新玩家头像昵称回复 */
        RummyUpdatePlayerInfoRsp = 13320,
        /**  登陆福利通知消息 */
        RummyLoginWelfareNtf = 13321,
        /**  领取破产补助通知 */
        RummyAwardBrokeHelpNtf = 13322,
        /**  领取破产补助请求 */
        RummyAwardBrokeHelpReq = 13323,
        /**  领取破产补助响应 */
        RummyAwardBrokeHelpRsp = 13324,
        /**  添加数据统计请求 */
        RummyAddDataTongJiReq = 13325,
        /**  添加数据统计请求响应 */
        RummyAddDataTongJiRsp = 13326,
        /**  显示地区选择界面通知 */
        RummyShowAreaSelectNtf = 13329,
        /**  选择地区请求 */
        RummySelectAreaReq = 13330,
        /**  选择地区请求响应 */
        RummySelectAreaRsp = 13331,
        /**  设置玩家昵称请求 */
        RummySetNameReq = 13332,
        /**  设置玩家昵称请求响应 */
        RummySetNameRsp = 13333,
        /**  设置玩家头像请求 */
        RummySetIconReq = 13334,
        /**  设置玩家头像请求响应 */
        RummySetIconRsp = 13335,
        /**  上报事件通知消息 */
        PutReportEventListNtf = 13336,
        /**  确认上报事件通知请求 */
        AckReportEventResultReq = 13337,
        /**  确认上报事件通知请求响应 */
        AckReportEventResultRsp = 13338,
        /**  设置玩家性别请求 */
        RummySetSexReq = 13339,
        /**  设置玩家性别请求响应 */
        RummySetSexRsp = 13340,
        /**  领取bonus cash 请求 */
        RummyAwardBonusCashReq = 13341,
        /**  领取bonus cash 请求响应 */
        RummyAwardBonusCashRsp = 13342,
        /**  rummy获取外链请求 */
        RummyGetLinkUrlReq = 13345,
        /**  rummy获取外链请求响应 */
        RummyGetLinkUrlRsp = 13346,
        /**  rummy获取外链游戏列表 */
        RummyGetLinkGameListReq = 13347,
        /**  rummy获取外链游戏列表响应 */
        RummyGetLinkGameListRsp = 13348,
        /**  rummy匹配请求 */
        RummyMatchReq = 8195,
        /**  rummy匹配应答 */
        RummyMatchRsp = 8196,
        /**  tp匹配请求 */
        TPMatchReq = 8197,
        /**  tp匹配应答 */
        TPMatchRsp = 8198,
        /**  rummy获取游戏场次列表请求 */
        TPGetLevelListReq = 8202,
        /**  rummy获取游戏场次列表回复 */
        TPGetLevelListRsp = 8203,
        /** tp 在线人数 */
        TPGetOnlineReq = 8204,
        /** rummy match */
        TPGetOnlineRsp = 8205,
        /** tp 历史记录 */
        TPPlayerHistoryReq = 8206,
        /** rummy match */
        TPPlayerHistoryRsp = 8207,
        /**  获取商城配置请求 */
        RummyShopGetConfigReq = 33025,
        /**  获取商城配置响应 */
        RummyShopGetConfigRsp = 33026,
        /**  商城充值请求 */
        RummyShopBuyReq = 33027,
        /**  商城充值响应 */
        RummyShopBuyRsp = 33028,
        /**  商城提现请求 */
        RummyShopWithDrawReq = 33029,
        /**  商城提现响应 */
        RummyShopWithDrawRsp = 33030,
        /**  获取提现列表请求 */
        RummyShopGetWithDrawReq = 33031,
        /**  获取提现列表响应 */
        RummyShopGetWithDrawRsp = 33032,
        /**  获取银行卡列表请求 */
        RummyGetBankCardReq = 33033,
        /**  获取银行卡列表响应 */
        RummyGetBankCardRsp = 33034,
        /**  添加银行卡请求 */
        RummyAddBankCardReq = 33035,
        /**  添加银行卡响应 */
        RummyAddBankCardRsp = 33036,
        /**  删除银行卡请求 */
        RummyDelBankCardReq = 33037,
        /**  删除银行卡响应 */
        RummyDelBankCardRsp = 33038,
        /**  选择银行卡请求 */
        RummySelectBankCardReq = 33039,
        /**  选择银行卡响应 */
        RummySelectBankCardRsp = 33040,
        /**  修改银行卡请求 */
        RummyModBankCardReq = 33051,
        /**  修改银行卡响应 */
        RummyModBankCardRsp = 33052,
        /**  创建充值订单请求 */
        RummyShopCreateOrderReq = 33041,
        /**  创建充值订单响应 */
        RummyShopCreateOrderRsp = 33042,
        /**  第1种UPI充值请求 */
        RummyShopUPIPayReq = 33043,
        /**  第1种UPI充值响应 */
        RummyShopUPIPayRsp = 33044,
        /**  第2,3种专属账号充值请求 */
        RummyShopCreateMyPayCardReq = 33045,
        /**  第2,3种专属账号充值响应 */
        RummyShopCreateMyPayCardRsp = 33046,
        /**  获取个人信息请求 */
        RummyGetUserCardReq = 33047,
        /**  获取个人信息响应 */
        RummyGetUserCardRsp = 33048,
        /**  保存个人信息请求 */
        RummySaveBankCardReq = 33049,
        /**  保存个人信息响应 */
        RummySaveBankCardRsp = 33050,
        /**  发送手机验证码请求 */
        RummyShopSendSmsReq = 33072,
        /**  发送手机验证码响应 */
        RummyShopSendSmsRsp = 33073,
        /**  获取钱包信息请求 */
        RummyShopGetWalletInfoReq = 33074,
        /**  获取钱包信息请求响应 */
        RummyShopGetWalletInfoRsp = 33075,
        /**  获取KYC信息请求 */
        RummyShopGetKycInfoReq = 33076,
        /**  获取KYC信息请求响应 */
        RummyShopGetKycInfoRsp = 33077,
        /**  设置KYC信息请求 */
        RummyShopSetKycInfoReq = 33078,
        /**  设置KYC信息请求响应 */
        RummyShopSetKycInfoRsp = 33079,
        /**  获取交易流水请求 */
        RummyShopGetTransactionReq = 33080,
        /**  获取交易流水请求响应 */
        RummyShopGetTransactionRsp = 33081,
        /**  充值成功通知 */
        RummyShopRechargeResultNtf = 33082,
        /**  绑定手机号请求 */
        RummyShopBindPhoneReq = 33083,
        /**  绑定手机号请求响应 */
        RummyShopBindPhoneRsp = 33084,
        /**  上传文件请求 */
        RummyShopUploadFileReq = 33085,
        /**  上传文件响应 */
        RummyShopUploadFileRsp = 33086,
        /**  [GRE]创建充值订单请求 */
        RummyShopCreateGreOrderReq = 33088,
        /**  [GRE]创建充值订单请求响应 */
        RummyShopCreateGreOrderRsp = 33089,
        /**  [RazePay]创建充值订单请求 */
        RummyShopCreateRazeOrderReq = 33090,
        /**  [RazePay]创建充值订单请求响应 */
        RummyShopCreateRazeOrderRsp = 33091,
        /**  获取充值入口配置请求 */
        RummyShopGetRechargeConfReq = 33092,
        /**  获取充值入口配置响应 */
        RummyShopGetRechargeConfRsp = 33093,
        /**  创建手动充值订单请求 */
        RummyShopManualRechargeReq = 33094,
        /**  创建手动充值订单响应 */
        RummyShopManualRechargeRsp = 33095,
        /**  创建充值订单请求 */
        RummyShoptmRechargeReq = 33096,
        /**  创建充值订单响应 */
        RummyShoptmRechargeRsp = 33097,
        /** 网赚提现请求 */
        RummyNetMoneyWithDrawReq = 33104,
        /** 网赚提现应答 */
        RummyNetMoneyWithDrawRsp = 33105,
        /** 获取提现配置请求 */
        RummyShopGetWithdrawConfReq = 33106,
        /** 获取提现配置应答 */
        RummyShopGetWithdrawConfRsp = 33107,
        /** 二元涨跌提现请求 */
        RummyBtcSvrWithDrawReq = 33108,
        /** 二元涨跌提现应答 */
        RummyBtcSvrWithDrawRsp = 33109,
        /** 获取拼多多充值列表请求 */
        RummyShopGetPDDRechargeListReq = 33110,
        /** 获取拼多多充值列表请求应答 */
        RummyShopGetPDDRechargeListRsp = 33111,
        /** 创建拼多多充值请求 */
        RummyShopCreatePDDRechargeReq = 33112,
        /** 创建拼多多充值请求应答 */
        RummyShopCreatePDDRechargeRsp = 33113,
        /** 加入拼多多充值请求 */
        RummyShopJoinPDDRechargeReq = 33114,
        /** 加入拼多多充值请求应答 */
        RummyShopJoinPDDRechargeRsp = 33115,
        /** 领取拼多多充值奖励请求 */
        RummyShopGetPDDRechargeAwardReq = 33116,
        /** 领取拼多多充值奖励请求应答 */
        RummyShopGetPDDRechargeAwardRsp = 33117,
        /** 获取玩家的rummy vip信息请求 */
        RummyGetVipInfoReq = 33121,
        /** 获取玩家的rummy vip信息请求应答 */
        RummyGetVipInfoRsp = 33122,
        /** vip等级变化通知消息 */
        RummyVipChangeNtf = 33123,
        /** 获取vip月卡数据请求 */
        RummyGetVipCardInfoReq = 33137,
        /** 获取vip月卡数据请求应答 */
        RummyGetVipCardInfoRsp = 33138,
        /** 购买vip月卡请求 */
        RummyBuyVipCardReq = 33139,
        /** 购买vip月卡请求应答 */
        RummyBuyVipCardRsp = 33140,
        /** 领取vip月卡请求 */
        RummyAwardVipCardReq = 33141,
        /** 领取vip月卡请求应答 */
        RummyAwardVipCardRsp = 33142,
        /** 获取双倍充值信息请求 */
        RummyShopGetDoubleChargeReq = 33143,
        /** 获取双倍充值信息请求应答 */
        RummyShopGetDoubleChargeRsp = 33144,
        /** 双倍充值信息请求 */
        RummyShopBuyDoubleChargeReq = 33145,
        /** 双倍充值信息请求应答 */
        RummyShopBuyDoubleChargeRsp = 33146,
        /** 设置充值信息请求 */
        RummyShopSetChargeInfoReq = 33147,
        /** 设置充值信息请求应答 */
        RummyShopSetChargeInfoRsp = 33148,
        /** 获取首充活动请求 */
        RummyShopGetFirstChargeReq = 33149,
        /** 获取首充活动请求应答 */
        RummyShopGetFirstChargeRsp = 33150,
        /** 获取充值成功未上报订单请求 */
        RummyShopGetUnReportOrderReq = 33153,
        /** 获取充值成功未上报订单请求应答 */
        RummyShopGetUnReportOrderRsp = 33154,
        /** 删除充值成功未上报订单请求 */
        RummyShopDelUnReportOrderReq = 33155,
        /** 删除充值成功未上报订单请求应答 */
        RummyShopDelUnReportOrderRsp = 33156,
        /** 首充礼包信息请求 */
        FirstChargeRewardInfoReq = 33169,
        /** 首充礼包信息响应 */
        FirstChargeRewardInfoRsp = 33170,
        /** 首充礼包领取请求 */
        FirstChargeRewardGetReq = 33171,
        /** 首充礼包领取响应 */
        FirstChargeRewardGetRsp = 33172,
        /** 获取提现红点状态请求 */
        RummyShopGetWithdrawRedReq = 33185,
        /** 获取提现红点状态响应 */
        RummyShopGetWithdrawRedRsp = 33186,
        /** 提现红点通知 */
        RummyShopWithdrawRedNtf = 33187,
        /** 获取大转盘信息请求 */
        BigRotateInfoReq = 33201,
        /** 获取大转盘信息响应 */
        BigRotateInfoRsp = 33202,
        /** 大转盘spin请求 */
        BigRotateSpinReq = 33203,
        /** 大转盘spin响应 */
        BigRotateSpinRsp = 33204,
        /** 获取充值订单列表 */
        GetOrderListReq = 33205,
        /** 获取充值订单列表 */
        GetOrderListRsp = 33206,
        /** 获取留言信息请求 */
        GetHelpInfoReq = 33207,
        /** 获取留言信息请求 */
        GetHelpInfoRsp = 33208,
        /** 发送留言信息 */
        SendHelpInfoReq = 33209,
        /** 发送留言信息 */
        SendHelpInfoRsp = 33210,
        /** 获取vip gift信息 */
        GetVipGitftInfoReq = 33211,
        /** 获取vip gift信息 */
        GetVipGitftInfoRsp = 33212,
        /** 领取bonus */
        GetVipGitftBonusReq = 33213,
        /** 领取bonus */
        GetVipGitftBonusRsp = 33214,
        /**  获取场景推荐请求 */
        SceneChargeReq = 33217,
        /**  获取场景推荐响应 */
        SceneChargeRsp = 33218,
        /**  获取三选一信息请求 */
        ThreeOneInfoReq = 33219,
        /**  获取三选一信息响应 */
        ThreeOneInfoRsp = 33220,
        /**  领取三选一请求 */
        ThreeOneGetReq = 33221,
        /**  领取三选一响应 */
        ThreeOneGetRsp = 33222,
        /**  获取大R活动请求 */
        GetLuckyStrikeReq = 33223,
        /**  获取大R活动请求响应 */
        GetLuckyStrikeRsp = 33224,
        /**  获取vip新月卡数据请求 */
        RummyGetVipNewCardInfoReq = 33225,
        /**  获取vip新月卡数据请求响应 */
        RummyGetVipNewCardInfoRsp = 33226,
        /**  购买vip新月卡请求响应 */
        RummyBuyVipNewCardReq = 33227,
        /**  购买vip新月卡请求响应响应 */
        RummyBuyVipNewCardRsp = 33228,
        /**  领取vip新月卡请求 */
        RummyAwardVipNewCardReq = 33229,
        /**  领取vip新月卡请求响应 */
        RummyAwardVipNewCardRsp = 33230,
        /**  获取每日充值spin数据请求 */
        ShopGetDailyPayInfoReq = 33233,
        /**  获取每日充值spin数据请求响应 */
        ShopGetDailyPayInfoRsp = 33234,
        /**  Spin每日充值请求 */
        ShopSpinDailyPayReq = 33235,
        /**  Spin每日充值请求响应 */
        ShopSpinDailyPayRsp = 33236,
        /** 添加cpf信息请求 */
        RechargeAddCpfReq = 33237,
        /** 添加cpf信息返回 */
        RechargeAddCpfRsp = 33238,
        /** 获取开斋节活动数据请求 */
        KaizhaiGetInfoReq = 33239,
        /** 获取开斋节活动数据请求响应 */
        KaizhaiGetInfoRsp = 33240,
        /** 领取开斋节活动奖励请求 */
        KaizhaiReceiveReq = 33241,
        /** 领取开斋节活动奖励请求响应 */
        KaizhaiReceiveRsp = 33242,
        /** 获取存钱罐数据请求 */
        SavingpotGetInfoReq = 33243,
        /** 获取存钱罐数据响应 */
        SavingpotGetInfoRsp = 33244,
        /** 存钱罐通知 */
        SavingpotNtf = 33245,
        /** 获取复购活动数据请求 */
        RepurchaseGetInfoReq = 33249,
        /** 获取复购活动数据响应 */
        RepurchaseGetInfoRsp = 33250,
        /** 复购活动通知 */
        RepurchaseNtf = 33251,
        /**  获取未读消息总数请求 */
        MailSvrGetUnReadSumReq = 20481,
        /**  获取未读消息总数应答 */
        MailSvrGetUnReadSumRsp = 20482,
        /**  获取邮件消息列表请求 */
        MailSvrGetMailListReq = 20483,
        /**  获取邮件消息列表应答 */
        MailSvrGetMailListRsp = 20484,
        /**  标记邮件为已读请求 */
        MailSvrSetReadTagReq = 20487,
        /**  标记邮件为已读应答 */
        MailSvrSetReadTagRsp = 20488,
        /**  删除邮件请求 */
        MailSvrDelMailReq = 20489,
        /**  删除邮件应答 */
        MailSvrDelMailRsp = 20490,
        /**  新邮件通知 */
        MailSvrNewMailNtf = 20495,
        /**  获取指定邮件扩展详情请求 */
        MailSvrGetMailDetailExtendReq = 20496,
        /**  获取指定邮件扩展详情应答 */
        MailSvrGetMailDetailExtendRsp = 20497,
        /**  领取附件奖励请求,附件支持多个物品 */
        MailSvrAwardAttachExtendReq = 20498,
        /**  领取附件奖励应答,附件支持多个物品 */
        MailSvrAwardAttachExtendRsp = 20499,
        /**  删除所有已读邮件请求 */
        MailSvrDelReadedMailReq = 20500,
        /**  删除所有已读邮件应答 */
        MailSvrDelReadedMailRsp = 20501,
        /** ROOM_BEGIN 消息区间开始 */
        ROOM_BEGIN = 65536,
        /**  进入桌子或重连请求 */
        RummyEnterDeskReq = 90112,
        /**  进入桌子或重连响应 */
        RummyEnterDeskRsp = 90113,
        /**  离开桌子请求 */
        RummyLeaveDeskReq = 90114,
        /**  离开桌子响应 */
        RummyLeaveDeskRsp = 90115,
        /**  Rummy游戏开始倒计时通知 */
        RummyReadyStartGameNtf = 90116,
        /**  Rummy游戏开始通知（开局直接发牌） */
        RummyStartGameNtf = 90117,
        /**  发定庄通知 */
        RummySetZhuangNtf = 90118,
        /**  发手牌通知 */
        RummyDealNtf = 90119,
        /**  玩牌通知 */
        RummyPlayCardNtf = 90120,
        /**  操作牌请求 */
        RummyOprCardReq = 90121,
        /**  操作牌响应 */
        RummyOprCardRsp = 90122,
        /**  操作牌通知 */
        RummyOprCardNtf = 90123,
        /**  确认牌组通知 */
        RummyFixCardNtf = 90124,
        /**  确定拆牌请求 */
        RummyFixCardReq = 90125,
        /**  确定拆牌响应 */
        RummyFixCardRsp = 90126,
        /**  游戏结算通知 */
        RummySettleNtf = 90127,
        /**  玩家进入桌子通知 */
        RummyEnterDeskNtf = 90128,
        /**  玩家离开桌子通知 */
        RummyLeaveDeskNtf = 90129,
        /**  玩家行为通知 */
        RummyPlayerActionNtf = 90130,
        /**  确认牌组玩家列表通知 */
        RummyFixCardPlayersNtf = 90131,
        /**  等待玩家进入通知 */
        RummyWaitStartGameNtf = 90132,
        /**  玩家弃牌通知 */
        RummyGiveUpNtf = 90133,
        /**  保存牌组请求 */
        RummySaveCardGroupReq = 90134,
        /**  保存牌组响应 */
        RummySaveCardGroupRsp = 90135,
        /**  总结算通知 */
        RummyTotalSettleNtf = 90136,
        /**  获取积分请求 */
        RummyGetScoreBoardReq = 90137,
        /**  获取积分响应 */
        RummyGetScoreBoardRsp = 90138,
        /**  获取上局结算请求 */
        RummyGetLastSettleReq = 90139,
        /**  获取上局结算响应 */
        RummyGetLastSettleRsp = 90140,
        /**  暂停桌子消息请求 */
        RummyPauseDeskMsgReq = 90141,
        /**  暂停桌子消息回复 */
        RummyPauseDeskMsgRsp = 90143,
        /**  多玩家行为通知 */
        RummyPlayerListActionNtf = 90144,
        /**  获取出牌列表请求 */
        RummyGetOutCardsReq = 90145,
        /**  获取出牌列表请求回复 */
        RummyGetOutCardsRsp = 90146,
        /**  进入桌子或重连请求 */
        TPEnterDeskReq = 90176,
        /**  进入桌子或重连请求回复 */
        TPEnterDeskRsp = 90177,
        /**  玩家进入桌子通知 */
        TPEnterDeskNtf = 90178,
        /**  离开桌子请求 */
        TPLeaveDeskReq = 90179,
        /**  离开桌子请求回复 */
        TPLeaveDeskRsp = 90180,
        /**  玩家离开桌子通知 */
        TPLeaveDeskNtf = 90181,
        /**  tp游戏等待玩家加入通知 */
        TPWaitStartGameNtf = 90182,
        /**  tp游戏开始倒计时通知 */
        TPReadyStartGameNtf = 90183,
        /**  tp游戏开始通知（开局直接发牌） */
        TPStartGameNtf = 90184,
        /**  发手牌通知 */
        TPDealNtf = 90185,
        /**  玩牌通知 */
        TPPlayCardNtf = 90186,
        /**  操作牌请求 */
        TPOprCardReq = 90187,
        /**  操作牌请求回复 */
        TPOprCardRsp = 90188,
        /**  操作牌通知 */
        TPOprCardNtf = 90189,
        /**  游戏结算通知 */
        TPSettleNtf = 90190,
        /**  玩家行为通知 */
        TPPlayerActionNtf = 90191,
        /**  多玩家行为通知 */
        TPPlayerListActionNtf = 90192,
        /**  站起消息请求 */
        TPStandUpDeskReq = 90193,
        /**  站起消息请求回复 */
        TPStandUpDeskRsp = 90194,
        /**  坐下消息请求 */
        TPSitDownDeskReq = 90195,
        /**  坐下消息请求回复 */
        TPSitDownDeskRsp = 90196,
        /**  暂停桌子消息请求 */
        TPPauseDeskMsgReq = 90197,
        /**  暂停桌子消息请求回复 */
        TPPauseDeskMsgRsp = 90198,
        /**  获取积分请求 */
        TPGetScoreBoardReq = 90199,
        /**  获取积分请求回复 */
        TPGetScoreBoardRsp = 90200,
        /**  比牌通知 */
        TPShowCardNtf = 90201,
        /**  发调试手牌通知 */
        TPDebugDealNtf = 90202,
        /**  回来消息请求 */
        TPComeBackReq = 90203,
        /**  回来消息请求回复 */
        TPComeBackRsp = 90204,
        /**  暂停游戏请求 */
        TPPauseGameReq = 90209,
        /**  暂停游戏请求回复 */
        TPPauseGameRsp = 90210,
        /**  暂停游戏请求通知 */
        TPPauseGameNtf = 90211,
        /**  引导提现通知 */
        TPWithdrawLoadNtf = 90212,
        /**  升场通知 */
        TPUpLevelNtf = 90213,
        /**  快捷聊天请求 */
        RummyQuickChatReq = 90240,
        /**  快捷聊天请求响应 */
        RummyQuickChatRsp = 90241,
        /**  快捷聊天通知 */
        RummyQuickChatNtf = 90242,
        /**  第一次真金玩牌 */
        RummyFirstPlayOnCashNtf = 90256,
        /**  通用事件上报通知 */
        RummyReportEventNtf = 90257,
        /** ROOM END 房间消息区间结束 */
        ROOM_END = 131071,
        /**  获取幸运大转盘请求 */
        ActivityRummyGetTurnTableReq = 20897,
        /**  获取幸运大转盘请求响应 */
        ActivityRummyGetTurnTableRsp = 20898,
        /**  大转盘抽奖请求 */
        ActivityRummyGoTurnTableReq = 20899,
        /**  大转盘抽奖请求响应 */
        ActivityRummyGoTurnTableRsp = 20900,
        /**  获取7日登陆信息请求 */
        ActivityGetLogin7InfoReq = 20913,
        /**  获取7日登陆信息请求响应 */
        ActivityGetLogin7InfoRsp = 20914,
        /**  领取7日登陆奖励请求 */
        ActivityAwardLogin7AwardReq = 20915,
        /**  领取7日登陆奖励请求响应 */
        ActivityAwardLogin7AwardRsp = 20916,
        /**  获取7日礼包请求 */
        ActivityGetLogin7SlotReq = 20917,
        /**  获取7日礼包请求响应 */
        ActivityGetLogin7SlotRsp = 20918,
        /**  Spin 7日礼包请求 */
        ActivitySpinLogin7SlotReq = 20919,
        /**  Spin 7日礼包请求响应 */
        ActivitySpinLogin7SlotRsp = 20920,
        /**  领取7日礼包请求 */
        ActivityAwardLogin7SlotReq = 20921,
        /**  领取7日礼包请求响应 */
        ActivityAwardLogin7SlotRsp = 20922,
        /**  生成链接请求 */
        FissionCopyLineReq = 20929,
        /**  生成链接响应 */
        FissionCopyLineRsp = 20930,
        /**  获取 Reward信息请求 */
        FissionGetRewardReq = 20931,
        /**  获取 Reward信息响应 */
        FissionGetRewardRsp = 20932,
        /**  获取 Referrals信息请求 */
        FissionGetReferralsReq = 20933,
        /**  获取 Referrals信息响应 */
        FissionGetReferralsRsp = 20934,
        /**  提现请求 */
        FissionWithdrawReq = 20935,
        /**  提现响应 */
        FissionWithdrawRsp = 20936,
        /**  配置请求 */
        FissionConfReq = 20937,
        /**  配置响应 */
        FissionConfRsp = 20938,
        /**  进入pdd活动页请求 */
        PddReq = 20881,
        /**  进入pdd活动页响应 */
        PddRsp = 20882,
        /**  进入分享页请求 */
        PddShareReq = 20883,
        /**  进入分享页响应 */
        PddShareRsp = 20884,
        /**  收益列表请求 */
        PddRebateListReq = 20885,
        /**  收益列表响应 */
        PddRebateListRsp = 20886,
        /**  提现请求 */
        PddWithdrawReq = 20887,
        /**  提现响应 */
        PddWithdrawRsp = 20888,
        /**  获取返利基本信息请求 */
        ActivityGetRebateInfoReq = 20864,
        /**  获取返利基本信息响应 */
        ActivityGetRebateInfoRsp = 20865,
        /**  获取每日返利记录请求 */
        ActivityGetDayRebateReq = 20866,
        /**  获取每日返利记录响应 */
        ActivityGetDayRebateRsp = 20867,
        /**  获取邀请好友列表请求 */
        ActivityGetFriendsReq = 20868,
        /**  获取邀请好友列表响应 */
        ActivityGetFriendsRsp = 20869,
        /**  获取返利排行榜请求 */
        ActivityGetRebateRankReq = 20870,
        /**  获取返利排行榜响应 */
        ActivityGetRebateRankRsp = 20871,
        /**  设置邀请玩家ID请求 */
        ActivitySetInvitorIDReq = 20872,
        /**  设置邀请玩家ID响应 */
        ActivitySetInvitorIDRsp = 20873,
        /**  获取邀请信息请求 */
        ActivityGetInvitorInfoReq = 20874,
        /**  获取邀请信息响应 */
        ActivityGetInvitorInfoRsp = 20875,
        /**  获取游戏记录列表请求 */
        ActivityGetGameRecordsReq = 20876,
        /**  获取游戏记录列表请求响应 */
        ActivityGetGameRecordsRsp = 20877,
        /**  获取夺宝列表请求 */
        ActivitySvrGetFightTreasureListReq = 20800,
        /**  获取夺宝列表应答 */
        ActivitySvrGetFightTreasureListRsp = 20801,
        /**  获取我的夺宝码请求 */
        ActivitySvrGetMyTreasureCodeReq = 20802,
        /**  获取我的夺宝码应答 */
        ActivitySvrGetMyTreasureCodeRsp = 20803,
        /**  获取兑宝列表请求 */
        ActivitySvrGetExchangeTreasureListReq = 20804,
        /**  获取兑宝列表应答 */
        ActivitySvrGetExchangeTreasureListRsp = 20805,
        /**  获取夺宝记录列表请求 */
        ActivitySvrGetFightTreasureRecordReq = 20806,
        /**  获取夺宝记录列表应答 */
        ActivitySvrGetFightTreasureRecordRsp = 20807,
        /**  夺宝下注请求 */
        ActivitySvrBuyCodeReq = 20808,
        /**  夺宝下注应答 */
        ActivitySvrBuyCodeRsp = 20809,
        /**  兑宝请求 */
        ActivitySvrExchangeCodeReq = 20816,
        /**  兑宝应答 */
        ActivitySvrExchangeCodeRsp = 20817,
        /**  开奖通知 */
        ActivitySvrOpenTreasureNtf = 20818,
        /**  获取夺宝任务历史请求(往期幸运儿)请求 */
        ActivitySvrGetFightTreasureHistoryReq = 20819,
        /**  获取夺宝任务历史应答 */
        ActivitySvrGetFightTreasureHistoryRsp = 20820,
        /**  获取夺宝任务信息请求 */
        ActivitySvrGetTreasureTaskReq = 20821,
        /**  获取夺宝任务信息应答 */
        ActivitySvrGetTreasureTaskRsp = 20822,
        /**  更新夺宝任务信息 */
        ActivitySvrUpdateTreasureTaskNtf = 20823,
        /**  分享夺宝任务请求 */
        ActivitySvrShareTreasureTaskReq = 20824,
        /**  分享夺宝任务应答 */
        ActivitySvrShareTreasureTaskRsp = 20825,
        /**  赢得夺宝卷通知 */
        ActivitySvrWinTreasureCardNtf = 20826,
        /**  夺宝广播消息 */
        ActivitySvrTreasureBroadcastNtf = 20832,
        /**  获取留言信息请求 */
        GetServiceMsgReq = 20945,
        /**  获取留言信息响应 */
        GetServiceMsgRsp = 20946,
        /**  发送留言信息请求 */
        SendServiceMsgReq = 20947,
        /**  发送留言信息响应 */
        SendServiceMsgRsp = 20948,
        /**  获取大转盘请求 */
        ActivityPrizeWheelInitReq = 20961,
        /**  获取大转盘请求响应 */
        ActivityPrizeWheelInitRsp = 20962,
        /**  大转盘抽奖请求 */
        ActivityPrizeWheelSpinReq = 20963,
        /**  大转盘抽奖请求响应 */
        ActivityPrizeWheelSpinRsp = 20964,
        /**  大转盘领奖请求 */
        ActivityPrizeWheelReceiveReq = 20965,
        /**  大转盘领奖请求响应 */
        ActivityPrizeWheelReceiveRsp = 20966,
        /** VIDEO_BEGIN 0x80 (录像消息尽量小) */
        VIDEO_MAJONG_FAPAI = 128,
        /** VIDEO_BEGIN 0x80 (录像消息尽量小) */
        VIDEO_MAJONG_HUANSANZHANG = 129,
        /**  获取玩家信息请求 */
        HALL_GET_PLAYER_INFO_REQ = 12289,
        /**  获取玩家信息应答 */
        HALL_GET_PLAYER_INFO_RSP = 12290,
        /**  获取玩家是否正在游戏中请求 */
        HALL_GET_PLAYER_STATE_REQ = 12291,
        /**  获取玩家是否正在游戏中应答 */
        HALL_GET_PLAYER_STATE_RSP = 12292,
        /**  获取游戏信息请求 */
        HALL_GET_GAME_LIST_INFO_REQ = 12293,
        /**  获取游戏信息应答 */
        HALL_GET_GAME_LIST_INFO_RSP = 12294,
        /**  实名认证请求 */
        HALL_REAL_NAME_REQ = 12295,
        /**  实名认证应答 */
        HALL_REAL_NAME_RSP = 12296,
        /**  更新玩家信息请求 */
        HALL_UPDATE_PLAYER_INFO_REQ = 12297,
        /**  更新玩家信息应答 */
        HALL_UPDATE_PLAYER_INFO_RSP = 12298,
        /**  获取充值信息请求 （已废弃） */
        GET_CHARGE_INFO_REQ = 12299,
        /**  获取充值信息应答 （已废弃） */
        GET_CHARGE_INFO_RSP = 12300,
        /**  充值请求 （已废弃） */
        CHARGE_REQ = 12301,
        /**  充值应答 （已废弃） */
        CHARGE_RSP = 12302,
        /**  获取玩家游戏信息请求 */
        HALL_GET_PLAYER_GAME_INFO_REQ = 12303,
        /**  获取玩家游戏信息应答 */
        HALL_GET_PLAYER_GAME_INFO_RSP = 12304,
        /**  发送验证码 */
        AUTH_CODE_REQ = 12305,
        /**  接收验证码 */
        AUTH_CODE_RSP = 12306,
        /**  校验验证码请求 */
        CHECK_AUTH_CODE_REQ = 12307,
        /**  校验验证码应答 */
        CHECK_AUTH_CODE_RSP = 12308,
        /**  获取绑定手机可以获得的奖励请求 */
        GET_BIND_PHONE_REWARD_REQ = 12309,
        /**  获取绑定手机可以获得的奖励应答 */
        GET_BIND_PHONE_REWARD_RSP = 12310,
        /**  绑定手机请求 */
        BIND_PHONE_REQ = 12311,
        /**  绑定手机应答 */
        BIND_PHONE_RSP = 12312,
        /**  修改手机请求 */
        CHANGE_PHONE_REQ = 12313,
        /**  修改手机应答d */
        CHANGE_PHONE_RSP = 12320,
        /**  校验密码请求 */
        CHECK_PASSWORD_REQ = 12321,
        /**  校验密码应答 */
        CHECK_PASSWORD_RSP = 12322,
        /**  修改密码请求 */
        CHANGE_PASSWORD_REQ = 12323,
        /**  修改密码应答 */
        CHANGE_PASSWORD_RSP = 12324,
        /**  重置密码请求 */
        RESET_PASSWORD_REQ = 12325,
        /**  重置密码应答 */
        RESET_PASSWORD_RSP = 12326,
        /**  货币变化通知 */
        MONEY_CHANGE_NTF = 12327,
        /** 校验手机账号是否存在 */
        CHECK_PHONE_REQ = 12328,
        /** 校验手机账号是否存在 */
        CHECK_PHONE_RSP = 12329,
        /** 绑定微信 */
        BIND_WECHAT_REQ = 12336,
        /** 绑定微信 */
        BIND_WECHAT_RSP = 12337,
        /** 设置密码 */
        SET_PASSWORD_REQ = 12338,
        /** 设置密码 */
        SET_PASSWORD_RSP = 12339,
        /** 获取充值商品列表 */
        GET_CHARGE_ITEMS_REQ = 12368,
        /** 获取充值商品列表 */
        GET_CHARGE_ITEMS_RSP = 12369,
        /** 创建充值订单 */
        CREATE_ORDER_REQ = 12370,
        /** 创建充值订单 */
        CREATE_ORDER_RSP = 12371,
        /** 苹果支付验证 */
        CHECK_APPLE_PAY_REQ = 12372,
        /** 苹果支付验证 */
        CHECK_APPLY_PAY_RSP = 12373,
        /** 支付到账通知 */
        CHARGE_RECEIVED_NTF = 12374,
        /** 换钱/提现 演示引导 */
        SHOW_DEMO_GUIDE_REQ = 12375,
        /** 换钱/提现 演示引导 */
        SHOW_DEMO_GUIDE_RSP = 12376,
        /** 支付验证 */
        CHECK_PAY_REQ = 12377,
        /** 支付验证 */
        CHECK_PAY_RSP = 12384,
        /** 支付验证 */
        VOTE_SURVEY_REQ = 12385,
        /** 支付验证 */
        VOTE_SURVEY_RSP = 12386,
        /** 玩家账号信息 */
        PLAYER_ACCOUNT_INFO_REQ = 12387,
        /** 玩家账号信息 */
        PLAYER_ACCOUNT_INFO_RSP = 12388,
        /** 封停账号通知 */
        SUSPEND_ACCOUNT_NTF = 12389,
        /**  HALL2.0 进入大厅请求 */
        HALL_ENTER_REQ = 12563,
        /**  HALL2.0 进入大厅回复 */
        HALL_ENTER_RSP = 12564,
        /**  HALL2.0 玩家选择地区请求 */
        HALL_PICK_AREA_REQ = 12567,
        /**  HALL2.0 玩家选择地区回复 */
        HALL_PICK_AREA_RSP = 12568,
        /**  HALL2.0 更新游戏列表 */
        HALL_UPDATE_GAME_LIST_REQ = 12569,
        /**  HALL2.0 更新游戏列表回复 */
        HALL_UPDATE_GAME_LIST_RSP = 12576,
        /**  HALL2.0 获取游戏场次列表 */
        HALL_GET_GAME_LEVEL_LIST_REQ = 12577,
        /**  HALL2.0 获取游戏场次列表回复 */
        HALL_GET_GAME_LEVEL_LIST_RSP = 12578,
        /**  HALL2.0 获取地区选择配置 */
        HALL_GET_AREA_CONFIG_REQ = 12579,
        /**  HALL2.0 获取地区选择配置回复 */
        HALL_GET_AREA_CONFIG_RSP = 12580,
        /**  HALL2.0 更新玩家引导信息请求 */
        HALL_UPDATE_GUIDE_INFO_REQ = 12581,
        /**  HALL2.0 更新玩家引导信息响应 */
        HALL_UPDATE_GUIDE_INFO_RSP = 12582,
        /**  HALL2.0 更新玩家引导信息请求 */
        HALL_GET_CURRENCY_INFO_REQ = 12583,
        /**  HALL2.0 更新玩家引导信息响应 */
        HALL_GET_CURRENCY_INFO_RSP = 12584,
        /**  玩家VIP变化通知 */
        HALL_VIP_CHANGE_NTF = 13056,
        /** 停服通知 */
        MSGSVR_STOP_NTF = 16388,
        /** 通知所有客户端下线 */
        MSGSVR_ALLCLI_NTF = 16389,
        /** 通用通知消息 */
        MSGSVR_MESSAGE_NTF = 16390,
        /**  进入语聊房间请求 */
        MSGSVR_ENTER_VOICE_ROOM_REQ = 16391,
        /**  进入语聊房间应答 */
        MSGSVR_ENTER_VOICE_ROOM_RSP = 16392,
        /**  离开语聊房间请求 */
        MSGSVR_LEAVE_VOICE_ROOM_REQ = 16393,
        /**  离开语聊房间应答 */
        MSGSVR_LEAVE_VOICE_ROOM_RSP = 16394,
        /**  获取语聊玩家信息请求 */
        MSGSVR_GET_VOICE_PLAYER_INFO_REQ = 16395,
        /**  获取语聊玩家信息应答 */
        MSGSVR_GET_VOICE_PLAYER_INFO_RSP = 16396,
        /** 语聊玩家状态变化通知消息 */
        MSGSVR_VOICE_STATE_CHANGE_NTF = 16397,
        /**  获取公告列表请求 */
        MsgSvrGetNoticeListReq = 16400,
        /**  获取公告列表请求应答 */
        MsgSvrGetNoticeListRsp = 16401,
        /**  已读公告请求 */
        MsgSvrReadNoticeReq = 16402,
        /**  已读公告请求应答 */
        MsgSvrReadNoticeRsp = 16403,
        /**  红点通知 */
        MsgSvrReadPointNtf = 16404,
        /**  获取排行榜请求 */
        RANKSVR_GET_RANK_REQ = 20993,
        /**  获取排行榜应答 */
        RANKSVR_GET_RANK_RSP = 20994,
        /**  获取我的排行数据请求 */
        RANKSVR_GET_MY_RANK_DATA_REQ = 20995,
        /**  获取我的排行数据应答 */
        RANKSVR_GET_MY_RANK_DATA_RSP = 20996,
        /** 落地页埋点消息 */
        BACK_BEGIN = 131072,
        /** 落地页埋点消息 */
        BACK_END = 135167,
    }

    enum Message {
    }

}
